version: "3"

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
      - frontend
      - auth-service
      - wine-service
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # Wine app frontend
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - auth-service
      - wine-service
    volumes:
      - ./frontend/build:/app
    ports:
      - 5000:80
    restart: on-failure

  # Authenticates
  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: ./auth_service
    ports:
      - 5001:5001
    restart: on-failure

  # Retrieves wine information
  wine-service:
    image: wine-service
    container_name: wine-service
    build:
      context: ./wine_service
    ports:
      - 5002:5002
    restart: on-failure
