version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - "/src/node_modules"
          key: "npm-packages"
      - run: yarn build
  test:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: yarn install
      - run: yarn test
  analyze:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: yarn audit
